# frozen_string_literal: true

require 'ets_to_hass/string_colors'
require 'ets_to_hass/info'
require 'xmlsimple'
require 'yaml'
require 'json'
require 'logger'
require 'fileutils'
require 'openssl'
require 'base64'
require 'stringio'

# decryption not yet in rubyzip 3.0
# once included, remove this and the code in rubyzip_aes
$LOAD_PATH.unshift(File.join(File.dirname(__dir__), 'rubyzip_aes', 'lib'))
require 'zip'

module EtsToHass
  # Import ETS project file and generate configuration for Home Assistant and KNXWeb
  class Generator
    # extension of ETS project file
    ETS_EXT = '.knxproj'
    # converters of group address integer address into representation
    GROUP_ADDRESS_PARSERS = {
      Free:       ->(a) { a.to_s },
      TwoLevel:   ->(a) { [(a >> 11) & 31, a & 2047].join('/') },
      ThreeLevel: ->(a) { [(a >> 11) & 31, (a >> 8) & 7, a & 255].join('/') }
    }.freeze
    # KNX functions described in knx_master.xml in project file, in <FunctionTypes>
    # map index parsed from "FT-x" to recognizable identifier
    ETS_FUNCTIONS_INDEX_TO_NAME =
      %i[custom switchable_light dimmable_light sun_protection heating_radiator heating_floor
         dimmable_light sun_protection heating_switching_variable heating_continuous_variable].freeze
    NOT_IMPLEMENTED = 'not_implemented'
    DESCR_MARKER = /^==ha==$/.freeze
    ETS_SALT = '21.project.ets.knx.org'
    private_constant :ETS_EXT, :ETS_FUNCTIONS_INDEX_TO_NAME, :NOT_IMPLEMENTED, :DESCR_MARKER, :ETS_SALT

    # class methods
    class << self
      # Generate ETS6 password from user password
      # @param password user password, as entered in ETS
      # @return ETS6 password, encrypted, as used in ZIP file
      def ets6_zip_password(password)
        Base64.strict_encode64(
          OpenSSL::PKCS5.pbkdf2_hmac(
            password.encode('utf-16le'),
            ETS_SALT,
            65_536,
            32,
            OpenSSL::Digest.new('sha256')
          )
        )
      end

      # helper function to dig through keys, knowing that we used ForceArray
      def dig_xml(entry_point, path)
        raise "ERROR: wrong entry point: #{entry_point.class}, expect Hash" unless entry_point.is_a?(Hash)

        path.each do |n|
          raise "ERROR: cannot find level #{n} in xml, have #{entry_point.keys.join(',')}" unless entry_point.key?(n)

          entry_point = entry_point[n]
          # because we use ForceArray
          # entry_point = entry_point.first
          raise "ERROR: expect array with one element in #{n}" if entry_point.nil?
        end
        entry_point
      end

      def function_type_to_name(ft_type)
        m = ft_type.match(/^FT-([0-9])$/)
        raise "ERROR: Unknown function type: #{ft_type}" if m.nil?

        ETS_FUNCTIONS_INDEX_TO_NAME[m[1].to_i]
      end

      def specific_defined?
        defined?(fix_objects).eql?('method')
      end
    end

    def initialize(file, options = {})
      # command line options
      @opts = options
      # parsed data: ob: objects (ETS functions), ga: group addresses
      @objects = {}
      @comments = {
        header: ['Generated by ets_to_hass', "Date: #{Time.now}"],
        footer: []
      }
      @project_id = nil
      @group_addresses = {}
      @associations = []
      # log to stderr, so that redirecting stdout captures only generated data
      @logger = Logger.new($stderr)
      @logger.level = @opts.key?(:trace) ? @opts[:trace] : Logger::INFO
      @logger.debug("options: #{@opts}")
      # read .knxproj file xml into project variable
      project = read_file(file)
      # find out address style
      proj_info = self.class.dig_xml(project[:info], %w[Project ProjectInformation])
      @group_addr_style = (@opts[:addr] || proj_info['GroupAddressStyle']).to_sym
      raise "Error: no such style #{@group_addr_style} in #{GROUP_ADDRESS_PARSERS.keys}" if GROUP_ADDRESS_PARSERS[@group_addr_style].nil?

      @logger.info("Using project #{proj_info['Name']}, address style: #{@group_addr_style}")
      # locate main node in xml
      installation = self.class.dig_xml(project[:data], %w[Project Installations Installation])
      # process group ranges: fill @group_addresses
      process_group_ranges(self.class.dig_xml(installation, %w[GroupAddresses GroupRanges]))
      # process group ranges: fill @objects (for 2 versions of ETS which have different tags?)
      process_space(self.class.dig_xml(installation, ['Locations']), 'Space') if installation.key?('Locations')
      process_space(self.class.dig_xml(installation, ['Buildings']), 'BuildingPart') if installation.key?('Buildings')
      @logger.warn('No building information found.') if @objects.keys.empty?
      return unless @opts[:specific]
      unless File.exist?(@opts[:specific])
        @logger.warn("Specific code file #{@opts[:specific]} not found, creating generic one.")
        FileUtils.cp(File.join(File.dirname(__FILE__), 'specific', 'generic.rb'), @opts[:specific])
      end
      # load specific code
      load(@opts[:specific])
      raise "no method found in #{@opts[:specific]}" unless self.class.specific_defined?
    end

    def warning(entity, name, message)
      @logger.warn("#{entity.red} #{name.green} #{message}")
    end

    # format the integer group address to string in desired style (e.g. 1/2/3)
    # @param group_address_int integer group address
    # @return string representation of group address
    def parse_group_address(group_address_int)
      GROUP_ADDRESS_PARSERS[@group_addr_style].call(group_address_int.to_i)
    end

    def read_project_info(projects, project_id, stream)
      project = (projects[project_id] ||= {})
      project[:info] = XmlSimple.xml_in(stream.read, { 'ForceArray' => false })
    end

    def read_project_data(projects, project_id, stream)
      project = (projects[project_id] ||= {})
      project[:data] = XmlSimple.xml_in(stream.read, { 'ForceArray' => %w[Space Function GroupAddressRef GroupRange GroupAddress] })
    end

    # Read both project.xml and 0.xml
    # @return Hash {info: xml data, data: xml data}
    def read_file(file)
      raise "ETS file must end with #{ETS_EXT}" unless file.end_with?(ETS_EXT)
      projects = {}
      # read ETS5 file and get project file
      Zip::File.open(file) do |zip_file|
        zip_file.each do |entry|
          case entry.name
          # when /^(P-[^.]+)\.signature$/
          when %r{^(P-[^/]+)/project\.xml$}
            read_project_info(projects, Regexp.last_match(1), entry.get_input_stream)
          when %r{^(P-[^/]+)/0\.xml$}
            read_project_data(projects, Regexp.last_match(1), entry.get_input_stream)
          when /^(P-[^.]+)\.zip$/
            raise 'Password protected project, provide option password.' unless @opts[:password]
            project_id = Regexp.last_match(1)
            ets6_pass = self.class.ets6_zip_password(@opts[:password])
            data = entry.get_input_stream.read
            Zip::InputStream.open(
              StringIO.new(data),
              decrypter: Zip::AESDecrypter.new(ets6_pass, Zip::AESEncryption::STRENGTH_256_BIT)
            ) do |zis|
              while (inner_entry = zis.get_next_entry)
                case inner_entry.name
                when /^project\.xml$/
                  read_project_info(projects, project_id, zis)
                when /^0\.xml$/
                  read_project_data(projects, project_id, zis)
                end
              end
            end
          end
        end
      end
      raise "Found more than 1 project: #{projects.keys}" unless projects.keys.length.eql?(1)
      projects.each do |k, v|
        raise "project.xml missing for #{k}" unless v.keys.include?(:info)
        raise "0.xml missing for #{k}" unless v.keys.include?(:data)
      end
      @project_id, project = projects.first
      @logger.info("Project: #{@project_id} found")
      project
    end

    # process group range recursively and find addresses
    def process_group_ranges(group)
      group['GroupRange'].each { |sgr| process_group_ranges(sgr) } if group.key?('GroupRange')
      group['GroupAddress'].each { |group_address_info| process_ga(group_address_info) } if group.key?('GroupAddress')
    end

    def extract_ha_from_description(description)
      return nil if description.nil?
      split_info = description.split(DESCR_MARKER, 2)
      return nil unless split_info.length.eql?(2)
      YAML.safe_load(split_info[1])
    end

    def process_ga_description(group, group_address_id)
      add_info = extract_ha_from_description(group[:description])
      return if add_info.nil?
      address_type = add_info.delete('address_type')
      group[:ha][:address_type] = address_type unless address_type.nil?
      object_name = add_info.delete('device_name')
      if object_name.nil?
        warning(group[:address], group[:name], 'additinal info in group address without device_name') unless add_info.empty?
        return
      end
      # for the time being, the object id is the device name, we assume it is unique
      object_id = object_name
      ets_object = object(object_id)
      unless ets_object
        # declare new object on the fly
        ets_object = {
          name: object_name,
          type: nil,
          ha:   { domain: nil } # hone assistant values
        }
        add_object(object_id, ets_object)
      end
      ets_object[:ha].merge!(add_info)
      associate(ga_id: group_address_id, object_id: object_id)
    end

    # process a group address
    def process_ga(group_address_info)
      # build object for each group address
      group = {
        name:        group_address_info['Name'], # ETS: name field
        description: group_address_info['Description'], # ETS: description field
        address:     parse_group_address(group_address_info['Address']), # group address as string. e.g. "x/y/z" depending on project style
        datapoint:   nil, # datapoint type as string "x.00y"
        ha:          { address_type: nil } # prepared to be potentially modified by specific code
      }
      process_ga_description(group, group_address_info['Id'])
      if group_address_info['DatapointType'].nil?
        warning(group[:address], group[:name], 'no datapoint type for address group, to be defined in ETS, skipping')
        return
      end
      # parse datapoint for easier use
      if (m = group_address_info['DatapointType'].match(/^DPST-([0-9]+)-([0-9]+)$/))
        # datapoint type as string x.00y
        group[:datapoint] = format('%d.%03d', m[1].to_i, m[2].to_i) # no freeze
      else
        warning(group[:address], group[:name],
                "Cannot parse data point type: #{group_address_info['DatapointType']} (DPST-x-x), skipping")
        return
      end
      # Index is the internal Id in xml file
      @group_addresses[group_address_info['Id']] = group.freeze
      @logger.debug("group: #{group}")
    end

    # process locations recursively, and find functions
    # @param space the current space
    # @param space_type the type of space: Space or BuildingPart
    # @param info current location information: floor, room
    def process_space(space, space_type, info = nil)
      info = info.nil? ? {} : info.dup
      @logger.debug("space: #{space['Type']}: #{space['Name']} (#{info})")
      # process building sub spaces
      if space.key?(space_type)
        # get floor when we have it
        info[:floor] = space['Name'] if space['Type'].eql?('Floor')
        # recursively process sub-spaces
        space[space_type].each { |s| process_space(s, space_type, info) }
      end
      # Functions are objects
      return unless space.key?('Function')

      # we assume the object is directly in the room
      info[:room] = space['Name']
      # loop on group addresses
      space['Function'].each do |ets_function|
        # @logger.debug("function #{ets_function}")
        # ignore functions without group address
        next unless ets_function.key?('GroupAddressRef')
        # the ETS object, created from ETS function
        ets_object = {
          name: ets_function['Name'],
          type: self.class.function_type_to_name(ets_function['Type']),
          ha:   { domain: nil } # hone assistant values
        }.merge(info)
        add_object(ets_function['Id'], ets_object)
        add_info = extract_ha_from_description(ets_function['Description'])
        ets_object[:ha].merge!(add_info) unless add_info.nil?
        ets_function['GroupAddressRef'].map { |g| g['RefId'] }.each do |group_address_id|
          associate(ga_id: group_address_id, object_id: ets_function['Id'])
        end
        @logger.debug("function: #{ets_object}")
      end
    end

    # map ETS function to home assistant object type
    # see https://www.home-assistant.io/integrations/knx/
    def map_ets_function_to_ha_object_category(ets_func)
      # map FT-x type to home assistant type
      case ets_func[:type]
      when :switchable_light, :dimmable_light then 'light'
      when :sun_protection then 'cover'
      when :custom, :heating_continuous_variable, :heating_floor, :heating_radiator, :heating_switching_variable
        @logger.warn("#{ets_func[:room].red} #{ets_func[:name].green} function type #{ets_func[:type].to_s.blue} not implemented")
        NOT_IMPLEMENTED
      else @logger.error("#{ets_func[:room].red} #{ets_func[:name].green} function type #{ets_func[:type].to_s.blue} not supported, please report")
           NOT_IMPLEMENTED
      end
    end

    # map datapoint to home assistant type
    # see https://www.home-assistant.io/integrations/knx/
    # @param domain the domain of the object (light, cover, etc...)
    # @param address the group address data
    def map_ets_datapoint_to_ha_address_type(domain:, address:)
      case address[:datapoint]
      when '1.001' then 'address' # switch on/off or state
      when '1.008' then 'move_long_address' # up/down
      when '1.010' then 'stop_address' # stop
      when '1.011' then 'state_address' # switch state
      when '3.007'
        @logger.debug("#{address[:address]}(#{domain}:#{address[:datapoint]}:#{address[:name]}): ignoring datapoint")
        nil # dimming control: used by buttons
      when '5.001' # percentage 0-100
        # user-provided code tells what is state
        case domain
        when 'light' then 'brightness_address'
        when 'cover' then 'position_address'
        else
          warning(address[:address], address[:name], "#{address[:datapoint]} expects: light or cover, not #{domain.magenta}")
          nil
        end
      else
        warning(address[:address], address[:name], "un-managed datapoint #{address[:datapoint].blue} (#{domain.magenta})")
        nil
      end
    end

    # @param ga_id group address id
    # @returns array of objects for this group id
    def ga_object_ids(ga_id)
      @associations.select { |a| a[:ga_id].eql?(ga_id) }.map { |a| a[:object_id] }
    end

    def all_object_ids
      @objects.keys
    end

    # @param object_id object id
    # @returns array of group addresses for this object
    def object_ga_ids(object_id)
      @associations.select { |a| a[:object_id].eql?(object_id) }.map { |a| a[:ga_id] }
    end

    def all_ga_ids
      @group_addresses.keys
    end

    def associate(ga_id:, object_id:)
      @associations.push({ ga_id: ga_id, object_id: object_id })
    end

    def delete_object(object_id)
      @objects.delete(object_id)
      @associations.delete_if { |a| a[:object_id].eql?(object_id) }
    end

    def add_object(object_id, object)
      # objects will not be modified, this shall be what comes from ETS only, use field `ha` for specific code
      @objects[object_id] = object.freeze
    end

    def object(object_id)
      @objects[object_id]
    end

    def group_address_data(ga_id)
      @group_addresses[ga_id]
    end

    def add_comment(comment)
      @comments[:footer].push(comment)
    end

    # This creates the Home Assistant configuration in variable ha_config
    # based on data coming from ETS
    # and optionally modified by specific code in apply_specific
    def generate_homeass
      # First, apply user-provided specific code
      if self.class.specific_defined?
        @logger.info("Applying fix code from #{@opts[:specific]}")
        fix_objects(self)
      end
      # This will be the YAML for HA
      ha_config = {}
      # warn of group addresses that will not be used (you can fix in specific code)
      all_ga_ids.each do |ga_id|
        next unless ga_object_ids(ga_id).empty?
        ga_data = group_address_data(ga_id)
        warning(ga_data[:address], ga_data[:name], 'Group not in object: use ETS to create functions or use specific code')
        add_comment("#{ga_data[:address]}: #{ga_data[:name]}") if @opts[:comment_skipped]
      end
      # Generate devices from either functions in ETS, or from specific code
      all_object_ids.each do |object_id|
        ets_object = object(object_id)
        # compute object domain, this is the section in HA configuration (switch, light, etc...)
        ha_object_domain = ets_object[:ha].delete(:domain) || map_ets_function_to_ha_object_category(ets_object)
        warning(ets_object[:name], ets_object[:room], "#{ets_object[:type].to_s.blue}: function type not mapped, skipping") if ha_object_domain.eql?(NOT_IMPLEMENTED)
        # add domain to config, if necessary
        ha_config[ha_object_domain] ||= []
        # HA configuration object, either empty or initialized in specific code
        ha_device = ets_object[:ha]
        # default name
        ha_device['name'] ||= @opts[:full_name] ? "#{ets_object[:name]} #{ets_object[:room]}" : ets_object[:name]
        # check name is not duplicated, as name is used to identify the object
        if ha_config[ha_object_domain].any? { |v| v['name'].casecmp?(ha_device['name']) }
          @logger.warn("#{ha_device['name'].red} object name is duplicated (check ETS objects and rooms)")
        end
        # add object to configuration
        ha_config[ha_object_domain].push(ha_device)
        # process all group addresses in ETS function (object)
        object_ga_ids(object_id).each do |group_address_id|
          # get this group information
          ga_data = group_address_data(group_address_id)
          if ga_data.nil?
            @logger.error("#{ets_object[:name].red} #{ets_object[:room].green} (#{ets_object[:type].to_s.magenta}): #{group_address_id}: group address not found, skipping")
            next
          end
          # find HA property name based on datapoint
          ha_address_type = ga_data[:ha][:address_type] || map_ets_datapoint_to_ha_address_type(address: ga_data, domain: ha_object_domain)
          next if ha_address_type.eql?(:ignore)
          if ha_address_type.nil?
            warning(ga_data[:address], ga_data[:name],
                    "#{ga_data[:datapoint].blue} / #{ha_object_domain.magenta}: address type not detected, skipping")
            next
          end
          if ha_device.key?(ha_address_type)
            @logger.error("#{ga_data[:address].red} #{ga_data[:name].green} (#{ha_object_domain.magenta}:#{ga_data[:datapoint]}) #{ha_address_type} already set with #{ha_device[ha_address_type]}, skipping")
            # TODO: support passive addresses ?
            next
          end
          # ok, we have the property name and group address
          ha_device[ha_address_type] = ga_data[:address]
        end
      end
      if @opts[:sort_by_name]
        @logger.info('Sorting by name')
        ha_config.each_value { |v| v.sort_by! { |o| o['name'] } }
      end
      # remove not implemented objects
      ha_config.delete(NOT_IMPLEMENTED)&.each do |o|
        add_comment("#{o}") if @opts[:comment_skipped]
      end
      # add knx level, if user asks for it
      ha_config = { 'knx' => ha_config } if @opts[:ha_knx]
      [
        @comments[:header].map { |l| "# #{l}" },
        ha_config.to_yaml,
        @comments[:footer].map { |l| "# #{l}" }
      ].flatten.join("\n")
    end

    # https://sourceforge.net/p/linknx/wiki/Object_Definition_section/
    def generate_linknx
      @group_addresses.values.sort { |a, b| a[:address] <=> b[:address] }.map do |ga_data|
        linknx_name = ga_data[:name]
        linknx_id = "id_#{ga_data[:address].gsub('/', '_')}"
        %Q(        <object type="#{ga_data[:datapoint]}" id="#{linknx_id}" gad="#{ga_data[:address]}" init="request">#{linknx_name}</object>)
      end.join("\n")
    end
  end
end
